name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Debug Flutter Setup
        run: |
          flutter channel
          flutter --version
          flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      # Step 4: Enable web support (if not already enabled)
      - name: Enable web support
        run: flutter config --enable-web

      # Step 5: Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web #--release

      # Step 6: Upload build artifacts (Optional, for inspection)
      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web/

      # Step 7: Deploy (Optional, Example: GitHub Pages)
      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: build/web
